/**
 * Copyright © 2018 Mercateo AG (http://www.mercateo.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mvnd.proto

package com.mercateo.oss.mvnd;

public final class MVNDProto {
  private MVNDProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InvokeRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mvnd.InvokeRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string workDir = 1;</code>
     */
    java.lang.String getWorkDir();
    /**
     * <code>optional string workDir = 1;</code>
     */
    com.google.protobuf.ByteString
        getWorkDirBytes();

    /**
     * <code>repeated string args = 2;</code>
     */
    java.util.List<java.lang.String>
        getArgsList();
    /**
     * <code>repeated string args = 2;</code>
     */
    int getArgsCount();
    /**
     * <code>repeated string args = 2;</code>
     */
    java.lang.String getArgs(int index);
    /**
     * <code>repeated string args = 2;</code>
     */
    com.google.protobuf.ByteString
        getArgsBytes(int index);
  }
  /**
   * Protobuf type {@code mvnd.InvokeRequest}
   */
  public  static final class InvokeRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mvnd.InvokeRequest)
      InvokeRequestOrBuilder {
    // Use InvokeRequest.newBuilder() to construct.
    private InvokeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InvokeRequest() {
      workDir_ = "";
      args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InvokeRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              workDir_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                args_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              args_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          args_ = args_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mercateo.oss.mvnd.MVNDProto.InvokeRequest.class, com.mercateo.oss.mvnd.MVNDProto.InvokeRequest.Builder.class);
    }

    private int bitField0_;
    public static final int WORKDIR_FIELD_NUMBER = 1;
    private volatile java.lang.Object workDir_;
    /**
     * <code>optional string workDir = 1;</code>
     */
    public java.lang.String getWorkDir() {
      java.lang.Object ref = workDir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workDir_ = s;
        return s;
      }
    }
    /**
     * <code>optional string workDir = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWorkDirBytes() {
      java.lang.Object ref = workDir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList args_;
    /**
     * <code>repeated string args = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getArgsList() {
      return args_;
    }
    /**
     * <code>repeated string args = 2;</code>
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated string args = 2;</code>
     */
    public java.lang.String getArgs(int index) {
      return args_.get(index);
    }
    /**
     * <code>repeated string args = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArgsBytes(int index) {
      return args_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWorkDirBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workDir_);
      }
      for (int i = 0; i < args_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, args_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWorkDirBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workDir_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < args_.size(); i++) {
          dataSize += computeStringSizeNoTag(args_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getArgsList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mercateo.oss.mvnd.MVNDProto.InvokeRequest)) {
        return super.equals(obj);
      }
      com.mercateo.oss.mvnd.MVNDProto.InvokeRequest other = (com.mercateo.oss.mvnd.MVNDProto.InvokeRequest) obj;

      boolean result = true;
      result = result && getWorkDir()
          .equals(other.getWorkDir());
      result = result && getArgsList()
          .equals(other.getArgsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + WORKDIR_FIELD_NUMBER;
      hash = (53 * hash) + getWorkDir().hashCode();
      if (getArgsCount() > 0) {
        hash = (37 * hash) + ARGS_FIELD_NUMBER;
        hash = (53 * hash) + getArgsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mercateo.oss.mvnd.MVNDProto.InvokeRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mvnd.InvokeRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mvnd.InvokeRequest)
        com.mercateo.oss.mvnd.MVNDProto.InvokeRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mercateo.oss.mvnd.MVNDProto.InvokeRequest.class, com.mercateo.oss.mvnd.MVNDProto.InvokeRequest.Builder.class);
      }

      // Construct using com.mercateo.oss.mvnd.MVNDProto.InvokeRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        workDir_ = "";

        args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeRequest_descriptor;
      }

      public com.mercateo.oss.mvnd.MVNDProto.InvokeRequest getDefaultInstanceForType() {
        return com.mercateo.oss.mvnd.MVNDProto.InvokeRequest.getDefaultInstance();
      }

      public com.mercateo.oss.mvnd.MVNDProto.InvokeRequest build() {
        com.mercateo.oss.mvnd.MVNDProto.InvokeRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mercateo.oss.mvnd.MVNDProto.InvokeRequest buildPartial() {
        com.mercateo.oss.mvnd.MVNDProto.InvokeRequest result = new com.mercateo.oss.mvnd.MVNDProto.InvokeRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.workDir_ = workDir_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          args_ = args_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.args_ = args_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mercateo.oss.mvnd.MVNDProto.InvokeRequest) {
          return mergeFrom((com.mercateo.oss.mvnd.MVNDProto.InvokeRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mercateo.oss.mvnd.MVNDProto.InvokeRequest other) {
        if (other == com.mercateo.oss.mvnd.MVNDProto.InvokeRequest.getDefaultInstance()) return this;
        if (!other.getWorkDir().isEmpty()) {
          workDir_ = other.workDir_;
          onChanged();
        }
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mercateo.oss.mvnd.MVNDProto.InvokeRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mercateo.oss.mvnd.MVNDProto.InvokeRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object workDir_ = "";
      /**
       * <code>optional string workDir = 1;</code>
       */
      public java.lang.String getWorkDir() {
        java.lang.Object ref = workDir_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workDir_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string workDir = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWorkDirBytes() {
        java.lang.Object ref = workDir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workDir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string workDir = 1;</code>
       */
      public Builder setWorkDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workDir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string workDir = 1;</code>
       */
      public Builder clearWorkDir() {
        
        workDir_ = getDefaultInstance().getWorkDir();
        onChanged();
        return this;
      }
      /**
       * <code>optional string workDir = 1;</code>
       */
      public Builder setWorkDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workDir_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureArgsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          args_ = new com.google.protobuf.LazyStringArrayList(args_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getArgsList() {
        return args_.getUnmodifiableView();
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public int getArgsCount() {
        return args_.size();
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public java.lang.String getArgs(int index) {
        return args_.get(index);
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArgsBytes(int index) {
        return args_.getByteString(index);
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public Builder setArgs(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
        args_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public Builder addArgs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureArgsIsMutable();
        args_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public Builder addAllArgs(
          java.lang.Iterable<java.lang.String> values) {
        ensureArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, args_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public Builder clearArgs() {
        args_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string args = 2;</code>
       */
      public Builder addArgsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mvnd.InvokeRequest)
    }

    // @@protoc_insertion_point(class_scope:mvnd.InvokeRequest)
    private static final com.mercateo.oss.mvnd.MVNDProto.InvokeRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mercateo.oss.mvnd.MVNDProto.InvokeRequest();
    }

    public static com.mercateo.oss.mvnd.MVNDProto.InvokeRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InvokeRequest>
        PARSER = new com.google.protobuf.AbstractParser<InvokeRequest>() {
      public InvokeRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InvokeRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InvokeRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InvokeRequest> getParserForType() {
      return PARSER;
    }

    public com.mercateo.oss.mvnd.MVNDProto.InvokeRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InvokeResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mvnd.InvokeResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .mvnd.InvokeResponse.ResponseType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .mvnd.InvokeResponse.ResponseType type = 1;</code>
     */
    com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType getType();

    /**
     * <code>optional string line = 2;</code>
     */
    java.lang.String getLine();
    /**
     * <code>optional string line = 2;</code>
     */
    com.google.protobuf.ByteString
        getLineBytes();

    /**
     * <code>optional int32 errorCode = 3;</code>
     */
    int getErrorCode();
  }
  /**
   * Protobuf type {@code mvnd.InvokeResponse}
   */
  public  static final class InvokeResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mvnd.InvokeResponse)
      InvokeResponseOrBuilder {
    // Use InvokeResponse.newBuilder() to construct.
    private InvokeResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InvokeResponse() {
      type_ = 0;
      line_ = "";
      errorCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InvokeResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              line_ = s;
              break;
            }
            case 24: {

              errorCode_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.class, com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code mvnd.InvokeResponse.ResponseType}
     */
    public enum ResponseType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OUT = 0;</code>
       */
      OUT(0),
      /**
       * <code>ERR = 1;</code>
       */
      ERR(1),
      /**
       * <code>EXIT = 2;</code>
       */
      EXIT(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>OUT = 0;</code>
       */
      public static final int OUT_VALUE = 0;
      /**
       * <code>ERR = 1;</code>
       */
      public static final int ERR_VALUE = 1;
      /**
       * <code>EXIT = 2;</code>
       */
      public static final int EXIT_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseType valueOf(int value) {
        return forNumber(value);
      }

      public static ResponseType forNumber(int value) {
        switch (value) {
          case 0: return OUT;
          case 1: return ERR;
          case 2: return EXIT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResponseType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
              public ResponseType findValueByNumber(int number) {
                return ResponseType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResponseType[] VALUES = values();

      public static ResponseType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResponseType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:mvnd.InvokeResponse.ResponseType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .mvnd.InvokeResponse.ResponseType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .mvnd.InvokeResponse.ResponseType type = 1;</code>
     */
    public com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType getType() {
      com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType result = com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType.valueOf(type_);
      return result == null ? com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType.UNRECOGNIZED : result;
    }

    public static final int LINE_FIELD_NUMBER = 2;
    private volatile java.lang.Object line_;
    /**
     * <code>optional string line = 2;</code>
     */
    public java.lang.String getLine() {
      java.lang.Object ref = line_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        line_ = s;
        return s;
      }
    }
    /**
     * <code>optional string line = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLineBytes() {
      java.lang.Object ref = line_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        line_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRORCODE_FIELD_NUMBER = 3;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 3;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType.OUT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getLineBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, line_);
      }
      if (errorCode_ != 0) {
        output.writeInt32(3, errorCode_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType.OUT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getLineBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, line_);
      }
      if (errorCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errorCode_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mercateo.oss.mvnd.MVNDProto.InvokeResponse)) {
        return super.equals(obj);
      }
      com.mercateo.oss.mvnd.MVNDProto.InvokeResponse other = (com.mercateo.oss.mvnd.MVNDProto.InvokeResponse) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getLine()
          .equals(other.getLine());
      result = result && (getErrorCode()
          == other.getErrorCode());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine().hashCode();
      hash = (37 * hash) + ERRORCODE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mercateo.oss.mvnd.MVNDProto.InvokeResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mvnd.InvokeResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mvnd.InvokeResponse)
        com.mercateo.oss.mvnd.MVNDProto.InvokeResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.class, com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.Builder.class);
      }

      // Construct using com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        line_ = "";

        errorCode_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mercateo.oss.mvnd.MVNDProto.internal_static_mvnd_InvokeResponse_descriptor;
      }

      public com.mercateo.oss.mvnd.MVNDProto.InvokeResponse getDefaultInstanceForType() {
        return com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.getDefaultInstance();
      }

      public com.mercateo.oss.mvnd.MVNDProto.InvokeResponse build() {
        com.mercateo.oss.mvnd.MVNDProto.InvokeResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mercateo.oss.mvnd.MVNDProto.InvokeResponse buildPartial() {
        com.mercateo.oss.mvnd.MVNDProto.InvokeResponse result = new com.mercateo.oss.mvnd.MVNDProto.InvokeResponse(this);
        result.type_ = type_;
        result.line_ = line_;
        result.errorCode_ = errorCode_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mercateo.oss.mvnd.MVNDProto.InvokeResponse) {
          return mergeFrom((com.mercateo.oss.mvnd.MVNDProto.InvokeResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mercateo.oss.mvnd.MVNDProto.InvokeResponse other) {
        if (other == com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getLine().isEmpty()) {
          line_ = other.line_;
          onChanged();
        }
        if (other.getErrorCode() != 0) {
          setErrorCode(other.getErrorCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mercateo.oss.mvnd.MVNDProto.InvokeResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mercateo.oss.mvnd.MVNDProto.InvokeResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>optional .mvnd.InvokeResponse.ResponseType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .mvnd.InvokeResponse.ResponseType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .mvnd.InvokeResponse.ResponseType type = 1;</code>
       */
      public com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType getType() {
        com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType result = com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType.valueOf(type_);
        return result == null ? com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .mvnd.InvokeResponse.ResponseType type = 1;</code>
       */
      public Builder setType(com.mercateo.oss.mvnd.MVNDProto.InvokeResponse.ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .mvnd.InvokeResponse.ResponseType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object line_ = "";
      /**
       * <code>optional string line = 2;</code>
       */
      public java.lang.String getLine() {
        java.lang.Object ref = line_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          line_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string line = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLineBytes() {
        java.lang.Object ref = line_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          line_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string line = 2;</code>
       */
      public Builder setLine(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string line = 2;</code>
       */
      public Builder clearLine() {
        
        line_ = getDefaultInstance().getLine();
        onChanged();
        return this;
      }
      /**
       * <code>optional string line = 2;</code>
       */
      public Builder setLineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        line_ = value;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 3;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 3;</code>
       */
      public Builder setErrorCode(int value) {
        
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 3;</code>
       */
      public Builder clearErrorCode() {
        
        errorCode_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:mvnd.InvokeResponse)
    }

    // @@protoc_insertion_point(class_scope:mvnd.InvokeResponse)
    private static final com.mercateo.oss.mvnd.MVNDProto.InvokeResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mercateo.oss.mvnd.MVNDProto.InvokeResponse();
    }

    public static com.mercateo.oss.mvnd.MVNDProto.InvokeResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InvokeResponse>
        PARSER = new com.google.protobuf.AbstractParser<InvokeResponse>() {
      public InvokeResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new InvokeResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InvokeResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InvokeResponse> getParserForType() {
      return PARSER;
    }

    public com.mercateo.oss.mvnd.MVNDProto.InvokeResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mvnd_InvokeRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mvnd_InvokeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mvnd_InvokeResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mvnd_InvokeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nmvnd.proto\022\004mvnd\".\n\rInvokeRequest\022\017\n\007w" +
      "orkDir\030\001 \001(\t\022\014\n\004args\030\002 \003(\t\"\216\001\n\016InvokeRes" +
      "ponse\022/\n\004type\030\001 \001(\0162!.mvnd.InvokeRespons" +
      "e.ResponseType\022\014\n\004line\030\002 \001(\t\022\021\n\terrorCod" +
      "e\030\003 \001(\005\"*\n\014ResponseType\022\007\n\003OUT\020\000\022\007\n\003ERR\020" +
      "\001\022\010\n\004EXIT\020\0022F\n\013MVNDService\0227\n\006invoke\022\023.m" +
      "vnd.InvokeRequest\032\024.mvnd.InvokeResponse\"" +
      "\0000\001B$\n\025com.mercateo.oss.mvndB\tMVNDProtoP" +
      "\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mvnd_InvokeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mvnd_InvokeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mvnd_InvokeRequest_descriptor,
        new java.lang.String[] { "WorkDir", "Args", });
    internal_static_mvnd_InvokeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mvnd_InvokeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mvnd_InvokeResponse_descriptor,
        new java.lang.String[] { "Type", "Line", "ErrorCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
