// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mvnd.proto

package mvnd

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InvokeResponse_ResponseType int32

const (
	InvokeResponse_OUT  InvokeResponse_ResponseType = 0
	InvokeResponse_ERR  InvokeResponse_ResponseType = 1
	InvokeResponse_EXIT InvokeResponse_ResponseType = 2
)

var InvokeResponse_ResponseType_name = map[int32]string{
	0: "OUT",
	1: "ERR",
	2: "EXIT",
}
var InvokeResponse_ResponseType_value = map[string]int32{
	"OUT":  0,
	"ERR":  1,
	"EXIT": 2,
}

func (x InvokeResponse_ResponseType) String() string {
	return proto.EnumName(InvokeResponse_ResponseType_name, int32(x))
}
func (InvokeResponse_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_mvnd_feb2c53428891fd5, []int{1, 0}
}

type InvokeRequest struct {
	WorkDir              string   `protobuf:"bytes,1,opt,name=workDir,proto3" json:"workDir,omitempty"`
	Args                 []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeRequest) Reset()         { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()    {}
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mvnd_feb2c53428891fd5, []int{0}
}
func (m *InvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeRequest.Unmarshal(m, b)
}
func (m *InvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeRequest.Marshal(b, m, deterministic)
}
func (dst *InvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeRequest.Merge(dst, src)
}
func (m *InvokeRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeRequest.Size(m)
}
func (m *InvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeRequest proto.InternalMessageInfo

func (m *InvokeRequest) GetWorkDir() string {
	if m != nil {
		return m.WorkDir
	}
	return ""
}

func (m *InvokeRequest) GetArgs() []string {
	if m != nil {
		return m.Args
	}
	return nil
}

type InvokeResponse struct {
	Type                 InvokeResponse_ResponseType `protobuf:"varint,1,opt,name=type,proto3,enum=mvnd.InvokeResponse_ResponseType" json:"type,omitempty"`
	Line                 string                      `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	ErrorCode            int32                       `protobuf:"varint,3,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *InvokeResponse) Reset()         { *m = InvokeResponse{} }
func (m *InvokeResponse) String() string { return proto.CompactTextString(m) }
func (*InvokeResponse) ProtoMessage()    {}
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_mvnd_feb2c53428891fd5, []int{1}
}
func (m *InvokeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeResponse.Unmarshal(m, b)
}
func (m *InvokeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeResponse.Marshal(b, m, deterministic)
}
func (dst *InvokeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeResponse.Merge(dst, src)
}
func (m *InvokeResponse) XXX_Size() int {
	return xxx_messageInfo_InvokeResponse.Size(m)
}
func (m *InvokeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeResponse proto.InternalMessageInfo

func (m *InvokeResponse) GetType() InvokeResponse_ResponseType {
	if m != nil {
		return m.Type
	}
	return InvokeResponse_OUT
}

func (m *InvokeResponse) GetLine() string {
	if m != nil {
		return m.Line
	}
	return ""
}

func (m *InvokeResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*InvokeRequest)(nil), "mvnd.InvokeRequest")
	proto.RegisterType((*InvokeResponse)(nil), "mvnd.InvokeResponse")
	proto.RegisterEnum("mvnd.InvokeResponse_ResponseType", InvokeResponse_ResponseType_name, InvokeResponse_ResponseType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MVNDServiceClient is the client API for MVNDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MVNDServiceClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (MVNDService_InvokeClient, error)
}

type mVNDServiceClient struct {
	cc *grpc.ClientConn
}

func NewMVNDServiceClient(cc *grpc.ClientConn) MVNDServiceClient {
	return &mVNDServiceClient{cc}
}

func (c *mVNDServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (MVNDService_InvokeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MVNDService_serviceDesc.Streams[0], "/mvnd.MVNDService/invoke", opts...)
	if err != nil {
		return nil, err
	}
	x := &mVNDServiceInvokeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MVNDService_InvokeClient interface {
	Recv() (*InvokeResponse, error)
	grpc.ClientStream
}

type mVNDServiceInvokeClient struct {
	grpc.ClientStream
}

func (x *mVNDServiceInvokeClient) Recv() (*InvokeResponse, error) {
	m := new(InvokeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MVNDServiceServer is the server API for MVNDService service.
type MVNDServiceServer interface {
	Invoke(*InvokeRequest, MVNDService_InvokeServer) error
}

func RegisterMVNDServiceServer(s *grpc.Server, srv MVNDServiceServer) {
	s.RegisterService(&_MVNDService_serviceDesc, srv)
}

func _MVNDService_Invoke_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InvokeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MVNDServiceServer).Invoke(m, &mVNDServiceInvokeServer{stream})
}

type MVNDService_InvokeServer interface {
	Send(*InvokeResponse) error
	grpc.ServerStream
}

type mVNDServiceInvokeServer struct {
	grpc.ServerStream
}

func (x *mVNDServiceInvokeServer) Send(m *InvokeResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _MVNDService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mvnd.MVNDService",
	HandlerType: (*MVNDServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "invoke",
			Handler:       _MVNDService_Invoke_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mvnd.proto",
}

func init() { proto.RegisterFile("mvnd.proto", fileDescriptor_mvnd_feb2c53428891fd5) }

var fileDescriptor_mvnd_feb2c53428891fd5 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xbb, 0x49, 0x6c, 0xcd, 0xa8, 0x25, 0xac, 0x0a, 0x41, 0x3c, 0xc4, 0xe0, 0x21, 0x78,
	0x08, 0x52, 0x11, 0x4f, 0x5e, 0x6a, 0x2b, 0xf4, 0xa0, 0x96, 0x35, 0x8a, 0xd7, 0x9a, 0x0e, 0x12,
	0x6a, 0x32, 0x71, 0x37, 0x46, 0xfa, 0x83, 0xfc, 0x9f, 0xb2, 0x03, 0x41, 0x0b, 0xde, 0xbe, 0x5d,
	0xde, 0xbc, 0xf7, 0x78, 0x00, 0x65, 0x5b, 0x2d, 0xd3, 0x5a, 0x53, 0x43, 0xd2, 0xb3, 0x1c, 0x5f,
	0xc3, 0xde, 0xac, 0x6a, 0x69, 0x85, 0x0a, 0x3f, 0x3e, 0xd1, 0x34, 0x32, 0x84, 0xc1, 0x17, 0xe9,
	0xd5, 0xa4, 0xd0, 0xa1, 0x88, 0x44, 0xe2, 0xab, 0xee, 0x29, 0x25, 0x78, 0x0b, 0xfd, 0x66, 0x42,
	0x27, 0x72, 0x13, 0x5f, 0x31, 0xc7, 0xdf, 0x02, 0x86, 0xdd, 0xbd, 0xa9, 0xa9, 0x32, 0x28, 0x2f,
	0xc1, 0x6b, 0xd6, 0x35, 0xf2, 0xf5, 0x70, 0x74, 0x92, 0x72, 0xe4, 0xa6, 0x26, 0xed, 0x20, 0x5b,
	0xd7, 0xa8, 0x58, 0x6e, 0xdd, 0xdf, 0x8b, 0x0a, 0x43, 0x87, 0x43, 0x99, 0xe5, 0x31, 0xf8, 0xa8,
	0x35, 0xe9, 0x1b, 0x5a, 0x62, 0xe8, 0x46, 0x22, 0xd9, 0x52, 0xbf, 0x1f, 0xf1, 0x19, 0xec, 0xfe,
	0xf5, 0x91, 0x03, 0x70, 0x1f, 0x9e, 0xb2, 0xa0, 0x67, 0x61, 0xaa, 0x54, 0x20, 0xe4, 0x36, 0x78,
	0xd3, 0x97, 0x59, 0x16, 0x38, 0xa3, 0x5b, 0xd8, 0xb9, 0x7b, 0xbe, 0x9f, 0x3c, 0xa2, 0x6e, 0x8b,
	0x1c, 0xe5, 0x15, 0xf4, 0x0b, 0x6e, 0x24, 0xf7, 0x37, 0xfb, 0xf1, 0x06, 0x47, 0x07, 0xff, 0x95,
	0x8e, 0x7b, 0xe7, 0x62, 0x7c, 0x0a, 0x87, 0x39, 0x95, 0x69, 0x89, 0x3a, 0x5f, 0x34, 0x48, 0x29,
	0x19, 0xc3, 0xda, 0xb1, 0x6f, 0xed, 0xe7, 0x76, 0xd8, 0x79, 0xef, 0xb5, 0xcf, 0x0b, 0x5f, 0xfc,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x42, 0xeb, 0xd1, 0x85, 0x6f, 0x01, 0x00, 0x00,
}
